name: 'build'

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 1 * * 6'

jobs:
  build:
    strategy:
      matrix:
        idf_ver: ["release-v4.2", "release-v4.3", "release-v4.4", "release-v5.0", "latest"]
        idf_target: ["esp32"]
        include:
          - idf_ver: "release-v4.2"
            idf_target: esp32s2
          - idf_ver: "release-v4.3"
            idf_target: esp32c3
          - idf_ver: "release-v4.4"
            idf_target: esp32s3
          - idf_ver: "release-v5.0"
            idf_target: esp32c2
    runs-on: ubuntu-22.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
          # idf_component.yml "override_path" feature requires the component directory name
          # to match the component name in the registry, so use 'libnmea' instead of 'libnmea-esp32'
          # when checking it out
          path: libnmea
      - name: Build for ${{ matrix.idf_target }}
        env:
          IDF_TARGET: ${{ matrix.idf_target }}
        shell: bash
        working-directory: example
        run: |
          . ${IDF_PATH}/export.sh
          idf.py build

  run-qemu:
    strategy:
      matrix:
        idf_ver: ["latest"]
        idf_target: ["esp32"]
    runs-on: ubuntu-22.04
    container: espressif/idf:${{ matrix.idf_ver }}
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
          # see the comment about checkout path in the job above
          path: libnmea
      - name: Install pytest
        shell: bash
        run: |
          . ${IDF_PATH}/export.sh
          pip install pytest-embedded pytest-embedded-qemu pytest-embedded-idf pytest-embedded-serial pytest-embedded-serial-esp
      - name: Build the example
        shell: bash
        working-directory: example
        run: |
          . ${IDF_PATH}/export.sh
          idf.py -DSDKCONFIG_DEFAULTS="sdkconfig.ci" build
      - name: Run the tests
        shell: bash
        working-directory: example
        run: |
          . ${IDF_PATH}/export.sh
          pytest
